source "https://rubygems.org"

gem "hacky_hal", :path => "../.."

# this should be a dependency in hacky_hal, but since it's not a gem yet, it can't be.
gem "upnp", :git => "https://github.com/turboladen/upnp.git"

gem "sinatra"
gem "thin"
